# Generated by Django 5.0.1 on 2024-05-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_attendance_enrollment_attendance_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='attended_time',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late_time',
        ),
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('Punch In', 'Punch In'), ('Punch Out', 'Punch Out')], max_length=10),
        ),
    ]
